apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: cm9vdA==
  password: MDExMjIwMDM=
  postdb_uri: bW9uZ29kYjovL3Jvb3Q6MDExMjIwMDNAcG9zdGRiLXN2YzoyNzAxNw==
  commentdb_uri: bW9uZ29kYjovL3Jvb3Q6MDExMjIwMDNAY29tbWVudGRiLXN2YzoyNzAxOA==
  authdb_uri: bW9uZ29kYjovL3Jvb3Q6MDExMjIwMDNAYXV0aGRiLXN2YzoyNzAxOQ==


# Example URI: mongodb://root:01122003@postdb-svc:27017
