apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /data/mongodb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commentdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard