apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /data/mongodb1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /data/mongodb2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /data/mongodb3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commentdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard